# Generated by Django 5.0.6 on 2024-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('high', 'High'), ('middle', 'Middle'), ('low', 'Low')], max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('coverage', models.FloatField()),
                ('description', models.TextField()),
                ('advantages', models.ManyToManyField(related_name='items', to='advert.advantage')),
                ('contacts', models.ManyToManyField(related_name='items', to='advert.contact')),
            ],
        ),
    ]
