from enum import Enum


# Перечисление для пола
class Gender(Enum):
    ALL = 'all'
    MALE = 'male'
    FEMALE = 'female'


# Перечисление для дохода
class Income(Enum):
    BC = 'bc'
    ABC = 'abc'


# Перечисление для категорий объектов
class Category(Enum):
    IL_DE_BOTE = 'Иль Де Ботэ'
    LAZURIT = 'Lazurit'
    ANTON = 'Anton'
    ZAGORYE = 'Загорье'
    Q_STORE = 'Q Store'
    MILE = 'Mile'


# Перечисление для районов (District)
class District(Enum):
    AKADEMICHEKSY_RAYON = 'Академический район'
    ALEKSEEVSKY_RAYON = 'Алексеевский район'
    ALTUFYEVSKY_RAYON = 'Алтуфьевский район'
    BABUSHKINSKY_RAYON = 'Бабушкинский район'
    BASMANNY_RAYON = 'Басманный район'
    BESKUDNIKOVSKY_RAYON = 'Бескудниковский район'
    BOGORODSKY_GORODSKOY_OKRUG = 'Богородский городской округ'
    BUTYRSKY_RAYON = 'Бутырский район'
    VOYKOVSKY_RAYON = 'Войковский район'
    GAGARINSKY_RAYON = 'Гагаринский район'
    GOLOVINSKY_RAYON = 'Головинский район'
    DANILOVSKY_RAYON = 'Даниловский район'
    DMITROVSKY_GORODSKOY_OKRUG = 'Дмитровский городской округ'
    DMITROVSKY_RAYON = 'Дмитровский район'
    DONSKOY_RAYON = 'Донской район'
    KRASNOSELSKY_RAYON = 'Красносельский район'
    LENINSKY_GORODSKOY_OKRUG = 'Ленинский городской округ'
    LOMONOSOVSKY_RAYON = 'Ломоносовский район'
    LOSINOOSTROVSKY_RAYON = 'Лосиноостровский район'
    MESHCHANSKY_RAYON = 'Мещанский район'
    MOZHAYSKY_RAYON = 'Можайский район'
    MOLZHANINOVSKY_RAYON = 'Молжаниновский район'
    NAGORNY_RAYON = 'Нагорный район'
    NARO_FOMINSKY_GORODSKOY_OKRUG = 'Наро-Фоминский городской округ'
    NIZHEGORODSKY_RAYON = 'Нижегородский район'
    NOVO_PEREDKINO = 'Ново-Переделкино'
    OBRUCHEVSKY_RAYON = 'Обручевский район'
    ODINTSOVSKY_GORODSKOY_OKRUG = 'Одинцовский городской округ'
    OREKHOVO_BORISOVO_YUZHNOE = 'Орехово-Борисово Южное'
    OSTANKINSKY_RAYON = 'Останкинский район'
    PRESNENSKY_RAYON = 'Пресненский район'
    PUSHKINSKY_GORODSKOY_OKRUG = 'Пушкинский городской округ'
    RAMENSKY_GORODSKOY_OKRUG = 'Раменский городской округ'
    RYAZANSKY_RAYON = 'Рязанский район'
    SAVYOLOVSKY_RAYON = 'Савёловский район'
    SERGIEVO_POSADSKY_GORODSKOY_OKRUG = 'Сергиево-Посадский городской округ'
    TAGANSKY_RAYON = 'Таганский район'
    TVERSKOY_RAYON = 'Тверской район'
    TIMIRYAZEVSKY_RAYON = 'Тимирязевский район'
    TROPAROVO_NIKULINO = 'Тропарёво-Никулино'
    KHOROSHEVSKY_RAYON = 'Хорошёвский район'
    YUZHNOPORTOVY_RAYON = 'Южнопортовый район'
    YAROSLAVSKY_RAYON = 'Ярославский район'
    BALASHIKHA = 'городской округ Балашиха'
    BRONNITSY = 'городской округ Бронницы'
    DZERZHINSKY = 'городской округ Дзержинский'
    DOLGOPRUDNY = 'городской округ Долгопрудный'
    DOMODEDOVO = 'городской округ Домодедово'
    ZHUKOVSKY = 'городской округ Жуковский'
    ISTRA = 'городской округ Истра'
    KLIN = 'городской округ Клин'
    KOLOMNA = 'городской округ Коломна'
    KOROLEV = 'городской округ Королёв'
    KOTELNIKI = 'городской округ Котельники'
    KRASNOGORSK = 'городской округ Красногорск'
    LOBNYA = 'городской округ Лобня'
    LYUBERTSY = 'городской округ Люберцы'
    MYTISHCHI = 'городской округ Мытищи'
    PODOLSK = 'городской округ Подольск'
    REUTOV = 'городской округ Реутов'
    SERPUKHOV = 'городской округ Серпухов'
    SOLNECHNOGORSK = 'городской округ Солнечногорск'
    FRYAZINO = 'городской округ Фрязино'
    KHIMKI = 'городской округ Химки'
    CHEKHOV = 'городской округ Чехов'
    SHCHERBINKA = 'городской округ Щербинка'
    SHCHELKOVO = 'городской округ Щёлково'
    ELEKTROSTAL = 'городской округ Электросталь'
    MOSRENTGEN = 'поселение «Мосрентген»'
    VNUKOVSKOYE = 'поселение Внуковское'
    DESYONOVSKOYE = 'поселение Десёновское'
    KRASNOPAKHORSKOYE = 'поселение Краснопахорское'
    MOSKOVSKY = 'поселение Московский'
    SOSENSKOYE = 'поселение Сосенское'
    FILIMONKOVSKOYE = 'поселение Филимонковское'
    ARBAT = 'район Арбат'
    AEROPORT = 'район Аэропорт'
    BEGOLOY = 'район Беговой'
    BIBIREVO = 'район Бибирево'
    BIRYULEVO_VOSTOCHNOE = 'район Бирюлёво Восточное'
    BIRYULEVO_ZAPADNOE = 'район Бирюлёво Западное'
    BOGORODSKOYE = 'район Богородское'
    BRATEEVO = 'район Братеево'
    VESHNYAKI = 'район Вешняки'
    VNIKOVO = 'район Внуково'
    VOSTOCHNOE_DEGUNINO = 'район Восточное Дегунино'
    VOSTOCHNOE_IZMAILOVO = 'район Восточное Измайлово'
    VYKHINO_ZHULEBINO = 'район Выхино-Жулебино'
    GOLYANOVO = 'район Гольяново'
    DOROGOMILOVO = 'район Дорогомилово'
    ZAMOSKVORECHYE = 'район Замоскворечье'
    ZAPADNOE_DEGUNINO = 'район Западное Дегунино'
    ZYUZINO = 'район Зюзино'
    ZYABLIKOVO = 'район Зябликово'
    IVANOVSKOYE = 'район Ивановское'
    IZMAILOVO = 'район Измайлово'
    KAPOTNYA = 'район Капотня'
    KONKOVO = 'район Коньково'
    KOPTEVO = 'район Коптево'
    KOSINO_UKHTOMSKY = 'район Косино-Ухтомский'
    KOTLOVKA = 'район Котловка'
    KRYLATSKOYE = 'район Крылатское'
    KRYUKOVO = 'район Крюково'
    KUZMINKI = 'район Кузьминки'
    KUNTSEVO = 'район Кунцево'
    LEVOBEREZHNY = 'район Левобережный'
    LEFORTOVO = 'район Лефортово'
    LIANOZOVO = 'район Лианозово'
    LYUBLINO = 'район Люблино'
    MARFINO = 'район Марфино'
    MARYINA_ROSHCHA = 'район Марьина Роща'
    MARYINO = 'район Марьино'
    MATUSHKINO = 'район Матушкино'
    METROGORODOK = 'район Метрогородок'
    MITINO = 'район Митино'
    MOSKVORECHYE_SABUROVO = 'район Москворечье-Сабурово'
    NAGATINO_SADOVNIKI = 'район Нагатино-Садовники'
    NAGATINSKY_ZATON = 'район Нагатинский Затон'
    NEKRASOVKA = 'район Некрасовка'
    NOVOGIREEVO = 'район Новогиреево'
    NOVOKOSINO = 'район Новокосино'
    OREKHOVO_BORISOVO_SEVERNOE = 'район Орехово-Борисово Северное'
    OTRADNOE = 'район Отрадное'
    OCHAKOVO_MATVEEVSKOYE = 'район Очаково-Матвеевское'
    PEROVO = 'район Перово'
    PECHATNIKI = 'район Печатники'
    POKROVSKOYE_STRESHNEVO = 'район Покровское-Стрешнево'
    PREOBRAZHENSKOYE = 'район Преображенское'
    PROSPEKT_VERNADSKOGO = 'район Проспект Вернадского'
    RAMENKI = 'район Раменки'
    ROSTOKINO = 'район Ростокино'
    SVIBLOVO = 'район Свиблово'
    SEVERNOE_BUTOVO = 'район Северное Бутово'
    SEVERNOE_IZMAILOVO = 'район Северное Измайлово'
    SEVERNOE_MEDVEDKOVO = 'район Северное Медведково'
    SEVERNOE_TUSHINO = 'район Северное Тушино'
    SEVERNY = 'район Северный'
    SOKOL = 'район Сокол'
    SOKOLINAYA_GORA = 'район Соколиная Гора'
    SOKOLNIKI = 'район Сокольники'
    SOLNTSEVO = 'район Солнцево'
    STAROE_KRYUKOVO = 'район Старое Крюково'
    STROGINO = 'район Строгино'
    TEKSTILSHCHIKI = 'район Текстильщики'
    TEPLOY_STAN = 'район Тёплый Стан'
    FILI_DAVYDKOVO = 'район Фили-Давыдково'
    FILEVSKY_PARK = 'район Филёвский Парк'
    KHAMOVNIKI = 'район Хамовники'
    KHOVRINO = 'район Ховрино'
    KHOROSHEVO_MNYOVNIKI = 'район Хорошёво-Мнёвники'
    TSARITSYNO = 'район Царицыно'
    CHERTANOVO_SEVERNOE = 'район Чертаново Северное'
    CHERTANOVO_TSENTRALNOE = 'район Чертаново Центральное'
    CHERTANOVO_YUZHNOE = 'район Чертаново Южное'
    CHERYOMUSHKI = 'район Черёмушки'
    SHCHUKINO = 'район Щукино'
    YUZHNOE_BUTOVO = 'район Южное Бутово'
    YUZHNOE_MEDVEDKOVO = 'район Южное Медведково'
    YUZHNOE_TUSHINO = 'район Южное Тушино'
    YAKIMANKA = 'район Якиманка'
    YASENOVO = 'район Ясенево'


# Перечисление для крупных районов (LargeArea)
class LargeArea(Enum):
    EAST_ADMINISTRATIVE_OKRUG = 'Восточный административный округ'
    WEST_ADMINISTRATIVE_OKRUG = 'Западный административный округ'
    ZELENOGRAD_ADMINISTRATIVE_OKRUG = 'Зеленоградский административный округ'
    MOSCOW_REGION = 'Московская область'
    NEW_MOSCOW_ADMINISTRATIVE_OKRUG = 'Новомосковский административный округ'
    NORTH_ADMINISTRATIVE_OKRUG = 'Северный административный округ'
    NORTHEAST_ADMINISTRATIVE_OKRUG = 'Северо-Восточный административный округ'
    NORTHWEST_ADMINISTRATIVE_OKRUG = 'Северо-Западный административный округ'
    TROITSKY_ADMINISTRATIVE_OKRUG = 'Троицкий административный округ'
    CENTRAL_ADMINISTRATIVE_OKRUG = 'Центральный административный округ'
    SOUTHEAST_ADMINISTRATIVE_OKRUG = 'Юго-Восточный административный округ'
    SOUTHWEST_ADMINISTRATIVE_OKRUG = 'Юго-Западный административный округ'
    SOUTH_ADMINISTRATIVE_OKRUG = 'Южный административный округ'

